#!/usr/bin/env bash
set -e

THIS_DIR="$(dirname "$0")"

python "$THIS_DIR/make_c_header.py" > "$THIS_DIR/gl_pre.h"

zig translate-c "$THIS_DIR/gl_pre.h" > "$THIS_DIR/gl_post.zig"

echo "// this file was generated by https://github.com/dbandstra/zig-gl"
echo ""
echo "const builtin = @import(\"builtin\");"
echo ""
echo "const cc: builtin.CallingConvention = if (builtin.os.tag == .windows) .StdCall else .C;"
echo ""
< "$THIS_DIR/gl_post.zig" perl -n -e '
    if (m/^pub const (khronos.+)$/) {
        print "const $1\n";
    }
'
echo ""
echo "pub const namespace = struct {"
< "$THIS_DIR/gl_post.zig" perl -n -e '
    if (m/^pub const GL/) {
        print "    $_";
    }
'
echo ""
< "$THIS_DIR/gl_post.zig" perl -n -e '
    if (m/^pub extern var (gl[a-zA-Z0-9_]+): \?fn \((.+)\) (.+);$/) {
        $_ = "    pub var $1: fn ($2) $3 = undefined;";
        s/callconv\(\.C\)/callconv(cc)/;
        print "$_\n";
    }
'
echo "};"
echo ""
echo "pub const Command = struct {"
echo "    name: [:0]const u8,"
echo "    ptr: **const c_void,"
echo "};"
echo ""
echo "pub const commands = [_]Command{"
< "$THIS_DIR/gl_post.zig" perl -n -e '
    if (m/^pub extern var (gl[a-zA-Z0-9_]+): \?fn/) {
        print "    Command{ .name = \"$1\", .ptr = \@ptrCast(**const c_void, &namespace.$1) },\n";
    }
'
echo "};"
