#!/bin/sh

SOURCEFILE="$1"
shift

if [ ! -f "$SOURCEFILE" ]; then
    echo "error: no SOURCEFILE" >&2
    exit 1
fi

echo "// this file was generated by https://github.com/dbandstra/zig-gl"
echo "//  version: $1"
shift
for GL_EXTENSION in "$@"; do
    echo "//  + $GL_EXTENSION"
done
echo
echo "const builtin = @import(\"builtin\");"
echo
echo "const cc: builtin.CallingConvention ="
echo "    if (builtin.os.tag == .windows and builtin.arch == .i386)"
echo "        .StdCall"
echo "    else"
echo "        .C;"
echo
grep '^pub const khronos' "$SOURCEFILE" | sed 's/^pub //' | sort
echo
grep '^pub const struct___GL' "$SOURCEFILE" | sed 's/^pub //' | sort
echo
echo "pub const namespace = struct {"
grep '^pub const GL[^_]' "$SOURCEFILE" | sort
echo
grep '^pub const GL_' "$SOURCEFILE" | sort
echo
perl -n -e '
if (/^pub extern var (gl[a-zA-Z0-9_]+): \?fn \((.+)\) (.+);$/) {
    $_ = "pub var $1: fn ($2) $3 = undefined;";
    s/callconv\(.+?\)/callconv(cc)/;
    print "$_\n";
}' < "$SOURCEFILE" | sort
echo "};"
echo
echo "pub const extensions = [_][:0]const u8{"
for GL_EXTENSION in "$@"; do
    echo "\"$GL_EXTENSION\","
done
echo "};"
echo
echo "pub const Command = struct {"
echo "    name: [:0]const u8,"
echo "    ptr: **const c_void,"
echo "};"
echo
echo "pub const commands = [_]Command{"
perl -n -e '
if (/^pub extern var (gl[a-zA-Z0-9_]+): \?fn/) {
    print ".{ .name = \"$1\", .ptr = \@ptrCast(**const c_void, &namespace.$1) },\n";
}' < "$SOURCEFILE" | sort
echo "};"
